In [2]:
import pandas as pd

In [3]:
df = pd.read_excel("../data/Online Retail.xlsx")

print("Dataset Shape:", df.shape)

df.head()

Dataset Shape: (541909, 8)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [4]:
print("Rows and Columns:", df.shape)

print("\nColumn Names:")
print(df.columns.tolist())

print("\nDataset Information:")
df.info()

Rows and Columns: (541909, 8)

Column Names:
['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country']

Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[us]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 40.0+ MB

In [5]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [6]:
missing = df.isnull().sum()

print("Missing Values:")
print(missing)

print("\nMissing Percentage:")
print((df.isnull().sum() / len(df) * 100).round(2))

Missing Values:
InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

Missing Percentage:
InvoiceNo       0.00
StockCode       0.00
Description     0.27
Quantity        0.00
InvoiceDate     0.00
UnitPrice       0.00
CustomerID     24.93
Country         0.00
dtype: float64

In [7]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 5268

In [8]:
cancelled = df['InvoiceNo'].astype(str).str.startswith('C')

print("Cancelled transactions:", cancelled.sum())
print("Normal transactions:", (~cancelled).sum())

Cancelled transactions: 9288
Normal transactions: 532621

In [9]:
print("Quantity <= 0:", (df['Quantity'] <= 0).sum())

print("\nMinimum Quantity:", df['Quantity'].min())
print("Maximum Quantity:", df['Quantity'].max())

Quantity <= 0: 10624

Minimum Quantity: -80995
Maximum Quantity: 80995

In [10]:
print("UnitPrice <= 0:", (df['UnitPrice'] <= 0).sum())

print("\nMinimum UnitPrice:", df['UnitPrice'].min())
print("Maximum UnitPrice:", df['UnitPrice'].max())

UnitPrice <= 0: 2517

Minimum UnitPrice: -11062.06
Maximum UnitPrice: 38970.0

In [11]:
print("UnitPrice <= 0:", (df['UnitPrice'] <= 0).sum())

print("\nMinimum UnitPrice:", df['UnitPrice'].min())
print("Maximum UnitPrice:", df['UnitPrice'].max())

UnitPrice <= 0: 2517

Minimum UnitPrice: -11062.06
Maximum UnitPrice: 38970.0

In [12]:
print("Unique StockCodes:", df['StockCode'].nunique())

print("\nTop 10 StockCodes:")
print(df['StockCode'].value_counts().head(10))

Unique StockCodes: 4070

Top 10 StockCodes:
StockCode
85123A    2313
22423     2203
85099B    2159
47566     1727
20725     1639
84879     1502
22720     1477
22197     1476
21212     1385
20727     1350
Name: count, dtype: int64

In [13]:
df[df['Description'].isnull()].head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.0,NaN,United Kingdom
1970,536545,21134,NaN,1,2010-12-01 14:32:00,0.0,NaN,United Kingdom
1971,536546,22145,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1972,536547,37509,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1987,536549,85226A,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
1988,536550,85044,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
2024,536552,20950,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
2025,536553,37461,NaN,3,2010-12-01 14:35:00,0.0,NaN,United Kingdom
2026,536554,84670,NaN,23,2010-12-01 14:35:00,0.0,NaN,United Kingdom
2406,536589,21777,NaN,-10,2010-12-01 16:50:00,0.0,NaN,United Kingdom

In [14]:
# Create a copy of the original dataset
df_clean = df.copy()

# 1. Remove duplicate rows
df_clean = df_clean.drop_duplicates()

# 2. Remove cancelled transactions
df_clean = df_clean[
    ~df_clean['InvoiceNo'].astype(str).str.startswith('C')
]

# 3. Keep only valid quantities
df_clean = df_clean[df_clean['Quantity'] > 0]

# 4. Keep only valid prices
df_clean = df_clean[df_clean['UnitPrice'] > 0]

# 5. Remove rows without CustomerID
df_clean = df_clean.dropna(subset=['CustomerID'])

# 6. Remove rows without product description
df_clean = df_clean.dropna(subset=['Description'])

# Reset index
df_clean = df_clean.reset_index(drop=True)

print("Original rows:", len(df))
print("Cleaned rows:", len(df_clean))
print("Rows removed:", len(df) - len(df_clean))

Original rows: 541909
Cleaned rows: 392692
Rows removed: 149217

In [15]:
print("Unique Customers:", df_clean['CustomerID'].nunique())
print("Unique Products:", df_clean['StockCode'].nunique())

print("\nCountries:", df_clean['Country'].nunique())

print("\nDate Range:")
print("From:", df_clean['InvoiceDate'].min())
print("To:", df_clean['InvoiceDate'].max())

Unique Customers: 4338
Unique Products: 3665

Countries: 37

Date Range:
From: 2010-12-01 08:26:00
To: 2011-12-09 12:50:00

In [16]:
# Create customer-product interaction matrix
interaction_matrix = df_clean.pivot_table(
    index='CustomerID',
    columns='StockCode',
    values='Quantity',
    aggfunc='sum',
    fill_value=0
)

print("Interaction Matrix Shape:", interaction_matrix.shape)

interaction_matrix.head()

Interaction Matrix Shape: (4338, 3665)

StockCode,10002,10080,10120,10125,10133,10135,11001,15030,15034,15036,...,90214V,90214W,90214Y,90214Z,BANK CHARGES,C2,DOT,M,PADS,POST
CustomerID,,,,,,,,,,,,,,,,,,,,,
12346.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12347.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12348.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,9
12349.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
12350.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [17]:
# Convert purchase quantities into binary interactions
interaction_binary = (interaction_matrix > 0).astype(int)

print("Binary Interaction Matrix Shape:", interaction_binary.shape)

print("\nTotal Purchases/Interactions:",
      interaction_binary.values.sum())

Binary Interaction Matrix Shape: (4338, 3665)

Total Purchases/Interactions: 266792

In [18]:
# Create train and test interactions
train_matrix = interaction_binary.copy()
test_matrix = interaction_binary.copy()

# For each customer, keep their last purchased product for testing
for customer in df_clean['CustomerID'].unique():
    
    customer_data = df_clean[df_clean['CustomerID'] == customer]
    
    # Last purchased product
    last_product = customer_data.sort_values('InvoiceDate').iloc[-1]['StockCode']
    
    # Remove it from training data
    if last_product in train_matrix.columns:
        train_matrix.loc[customer, last_product] = 0

print("Training Matrix Shape:", train_matrix.shape)
print("Test Matrix Shape:", test_matrix.shape)

Training Matrix Shape: (4338, 3665)
Test Matrix Shape: (4338, 3665)

In [21]:
from sklearn.decomposition import TruncatedSVD

# Convert all product column names to strings
train_matrix.columns = train_matrix.columns.astype(str)

# Number of latent factors
n_components = 50

# Create SVD model
svd = TruncatedSVD(
    n_components=n_components,
    random_state=42
)

# Train the model
customer_factors = svd.fit_transform(train_matrix)

# Product factors
product_factors = svd.components_

print("Customer Factors Shape:", customer_factors.shape)
print("Product Factors Shape:", product_factors.shape)

print("\nExplained Variance Ratio:",
      svd.explained_variance_ratio_.sum())

Customer Factors Shape: (4338, 50)
Product Factors Shape: (50, 3665)

Explained Variance Ratio: 0.27824046588097445

In [22]:
# Generate predicted interaction scores
predicted_scores = customer_factors @ product_factors

print("Predicted Scores Shape:", predicted_scores.shape)

Predicted Scores Shape: (4338, 3665)

In [24]:
# Function to generate recommendations
def get_recommendations(customer_id, top_n=10):
    
    # Get customer position
    customer_index = interaction_binary.index.get_loc(customer_id)
    
    # Get predicted scores for this customer
    scores = predicted_scores[customer_index]
    
    # Get products already purchased
    purchased_products = interaction_binary.loc[customer_id]
    
    # Copy scores so we can modify them
    recommendation_scores = pd.Series(
        scores,
        index=train_matrix.columns
    )
    
    # Remove already purchased products
    recommendation_scores[purchased_products.values == 1] = -1
    
    # Get top recommendations
    top_products = recommendation_scores.sort_values(
        ascending=False
    ).head(top_n)
    
    return top_products
    # Test recommendation for first customer
customer_id = interaction_binary.index[0]

recommendations = get_recommendations(customer_id, top_n=10)

print("Customer ID:", customer_id)
print("\nRecommended Products:")
print(recommendations)

Customer ID: 12346.0

Recommended Products:
StockCode
POST      0.0
90214N    0.0
90214M    0.0
90214L    0.0
90214K    0.0
90214J    0.0
90214I    0.0
90214H    0.0
90214G    0.0
90214F    0.0
dtype: float64

In [25]:
# Count purchases for each customer
customer_purchase_counts = interaction_binary.sum(axis=1)

# Customer with the highest number of different products purchased
active_customer = customer_purchase_counts.idxmax()

print("Selected Customer:", active_customer)
print("Products Purchased:", customer_purchase_counts[active_customer])

Selected Customer: 14911.0
Products Purchased: 1787

In [26]:
# Generate recommendations for an active customer
customer_id = active_customer

recommendations = get_recommendations(
    customer_id,
    top_n=10
)

print("Customer ID:", customer_id)
print("\nTop 10 Recommended Products:")
print(recommendations)

Customer ID: 14911.0

Top 10 Recommended Products:
StockCode
23051     0.621214
23053     0.618770
22074     0.563866
21123     0.563684
22521     0.561622
21928     0.547881
21395     0.514866
21618     0.504354
85049G    0.482037
23089     0.474758
dtype: float64

In [27]:
# Create a product information table
product_info = (
    df_clean[['StockCode', 'Description']]
    .drop_duplicates('StockCode')
    .copy()
)

# Make StockCode string for matching
product_info['StockCode'] = product_info['StockCode'].astype(str)

# Convert recommendations into a DataFrame
recommendation_df = recommendations.reset_index()

recommendation_df.columns = ['StockCode', 'Score']

# Make StockCode string
recommendation_df['StockCode'] = recommendation_df['StockCode'].astype(str)

# Add product descriptions
recommendation_df = recommendation_df.merge(
    product_info,
    on='StockCode',
    how='left'
)

# Arrange columns
recommendation_df = recommendation_df[
    ['StockCode', 'Description', 'Score']
]

print(recommendation_df)

  StockCode                          Description     Score
0     23051           RECYCLED ACAPULCO MAT BLUE  0.621214
1     23053           RECYCLED ACAPULCO MAT PINK  0.618770
2     22074          6 RIBBONS SHIMMERING PINKS   0.563866
3     21123  SET/10 IVORY POLKADOT PARTY CANDLES  0.563684
4     22521            CHILDS GARDEN TROWEL PINK  0.561622
5     21928       JUMBO BAG SCANDINAVIAN PAISLEY  0.547881
6     21395                BLUE POLKADOT BEAKER   0.514866
7     21618       4 WILDFLOWER BOTANICAL CANDLES  0.504354
8    85049G               CHOCOLATE BOX RIBBONS   0.482037
9     23089                    GLASS BON BON JAR  0.474758

In [28]:
import numpy as np

def precision_at_k(actual, recommended, k=10):
    recommended = recommended[:k]
    if len(recommended) == 0:
        return 0.0
    
    hits = len(set(actual) & set(recommended))
    return hits / k


def recall_at_k(actual, recommended, k=10):
    recommended = recommended[:k]
    if len(actual) == 0:
        return 0.0
    
    hits = len(set(actual) & set(recommended))
    return hits / len(actual)


def ndcg_at_k(actual, recommended, k=10):
    recommended = recommended[:k]
    
    relevance = [
        1 if item in actual else 0
        for item in recommended
    ]
    
    dcg = sum(
        rel / np.log2(i + 2)
        for i, rel in enumerate(relevance)
    )
    
    ideal_relevance = sorted(relevance, reverse=True)
    
    idcg = sum(
        rel / np.log2(i + 2)
        for i, rel in enumerate(ideal_relevance)
    )
    
    if idcg == 0:
        return 0.0
    
    return dcg / idcg

In [29]:
# Evaluate the recommendation model

k = 10

precision_scores = []
recall_scores = []
ndcg_scores = []

for customer_id in interaction_binary.index:

    # Products actually purchased by customer
    actual_products = set(
        test_matrix.loc[customer_id][
            test_matrix.loc[customer_id] == 1
        ].index
    )

    # We only evaluate customers with at least one purchase
    if len(actual_products) == 0:
        continue

    # Get recommendations
    recs = get_recommendations(
        customer_id,
        top_n=k
    )

    recommended_products = list(recs.index)

    # Calculate metrics
    precision_scores.append(
        precision_at_k(
            actual_products,
            recommended_products,
            k
        )
    )

    recall_scores.append(
        recall_at_k(
            actual_products,
            recommended_products,
            k
        )
    )

    ndcg_scores.append(
        ndcg_at_k(
            actual_products,
            recommended_products,
            k
        )
    )

# Average metrics
avg_precision = np.mean(precision_scores)
avg_recall = np.mean(recall_scores)
avg_ndcg = np.mean(ndcg_scores)

print("Model Evaluation Results")
print("------------------------")
print(f"Precision@10: {avg_precision:.4f}")
print(f"Recall@10:    {avg_recall:.4f}")
print(f"NDCG@10:      {avg_ndcg:.4f}")

Model Evaluation Results
------------------------
Precision@10: 0.0000
Recall@10:    0.0000
NDCG@10:      0.0000

In [30]:
# Create a proper test set containing only the last purchase of each customer

test_items = {}

for customer_id in df_clean['CustomerID'].unique():

    customer_data = df_clean[
        df_clean['CustomerID'] == customer_id
    ].sort_values('InvoiceDate')

    last_product = str(
        customer_data.iloc[-1]['StockCode']
    )

    test_items[customer_id] = last_product

print("Number of test customers:", len(test_items))
print("Example:", list(test_items.items())[:5])

Number of test customers: 4338
Example: [(np.float64(17850.0), '22633'), (np.float64(13047.0), 'M'), (np.float64(12583.0), '22726'), (np.float64(13748.0), '23012'), (np.float64(15100.0), '21258')]

In [31]:
def get_recommendations(customer_id, top_n=10):

    # Get customer position
    customer_index = train_matrix.index.get_loc(customer_id)

    # Get predicted scores
    scores = predicted_scores[customer_index]

    # Create score series
    recommendation_scores = pd.Series(
        scores,
        index=train_matrix.columns
    )

    # Remove products already purchased in TRAINING data
    purchased_products = train_matrix.loc[customer_id]

    recommendation_scores[
        purchased_products.values == 1
    ] = -1

    # Return top recommendations
    return recommendation_scores.sort_values(
        ascending=False
    ).head(top_n)

In [32]:
k = 10

precision_scores = []
recall_scores = []
ndcg_scores = []

for customer_id, actual_product in test_items.items():

    recommendations = get_recommendations(
        customer_id,
        top_n=k
    )

    recommended_products = list(recommendations.index)

    actual_products = {actual_product}

    precision_scores.append(
        precision_at_k(
            actual_products,
            recommended_products,
            k
        )
    )

    recall_scores.append(
        recall_at_k(
            actual_products,
            recommended_products,
            k
        )
    )

    ndcg_scores.append(
        ndcg_at_k(
            actual_products,
            recommended_products,
            k
        )
    )

print("Model Evaluation Results")
print("------------------------")
print(f"Precision@10: {np.mean(precision_scores):.4f}")
print(f"Recall@10:    {np.mean(recall_scores):.4f}")
print(f"NDCG@10:      {np.mean(ndcg_scores):.4f}")

Model Evaluation Results
------------------------
Precision@10: 0.0161
Recall@10:    0.1609
NDCG@10:      0.0955

In [33]:
# Keep only product codes that exist in our trained product matrix

valid_products = set(train_matrix.columns)

test_items_clean = {
    customer_id: product
    for customer_id, product in test_items.items()
    if product in valid_products
}

print("Total test customers:", len(test_items))
print("Valid test customers:", len(test_items_clean))
print("Removed test customers:", len(test_items) - len(test_items_clean))

print("\nExample valid test items:")
print(list(test_items_clean.items())[:5])

Total test customers: 4338
Valid test customers: 4338
Removed test customers: 0

Example valid test items:
[(np.float64(17850.0), '22633'), (np.float64(13047.0), 'M'), (np.float64(12583.0), '22726'), (np.float64(13748.0), '23012'), (np.float64(15100.0), '21258')]

In [34]:
# Identify non-product/service transactions
non_product_keywords = [
    'POSTAGE',
    'CHARGES',
    'MANUAL',
    'DISCOUNT',
    'FEE',
    'SAMPLE',
    'ADJUSTMENT'
]

# Create product information
product_info_clean = (
    df_clean[['StockCode', 'Description']]
    .drop_duplicates('StockCode')
    .copy()
)

# Find non-product stock codes
non_product_codes = product_info_clean[
    product_info_clean['Description']
    .str.upper()
    .str.contains('|'.join(non_product_keywords), na=False)
]['StockCode'].astype(str).tolist()

print("Non-product codes found:", len(non_product_codes))
print(non_product_codes[:20])

Non-product codes found: 28
['POST', '37370', '21662', 'M', '21398', '22301', '21216', '85159A', 'BANK CHARGES', '21399', '22300', '22304', '35810B', '22305', '20748', '72122', '22932', '85159B', '22302', '22970']

In [35]:
# Clearly non-product/service stock codes
non_product_codes = ['POST', 'M', 'BANK CHARGES']

# Remove them from the cleaned transaction data
df_model = df_clean[
    ~df_clean['StockCode'].astype(str).isin(non_product_codes)
].copy()

print("Original cleaned rows:", len(df_clean))
print("Rows after removing non-product codes:", len(df_model))
print("Rows removed:", len(df_clean) - len(df_model))

print("\nNon-product codes removed:", non_product_codes)

Original cleaned rows: 392692
Rows after removing non-product codes: 391302
Rows removed: 1390

Non-product codes removed: ['POST', 'M', 'BANK CHARGES']

In [36]:
# Make sure StockCode is treated consistently as text
df_model['StockCode'] = df_model['StockCode'].astype(str)

# Create Customer-Product interaction matrix
interaction_matrix = df_model.pivot_table(
    index='CustomerID',
    columns='StockCode',
    values='Quantity',
    aggfunc='sum',
    fill_value=0
)

print("Interaction Matrix Shape:", interaction_matrix.shape)
interaction_matrix.head()

Interaction Matrix Shape: (4334, 3662)

StockCode,10002,10080,10120,10123C,10124A,10124G,10125,10133,10135,11001,...,90214S,90214T,90214U,90214V,90214W,90214Y,90214Z,C2,DOT,PADS
CustomerID,,,,,,,,,,,,,,,,,,,,,
12346.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12347.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12348.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12349.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12350.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [37]:
print("Total interactions:", (interaction_matrix > 0).sum().sum())
print("Non-zero values:", (interaction_matrix > 0).sum().sum())
print("Total values:", interaction_matrix.size)
print("Customers:", interaction_matrix.shape[0])
print("Products:", interaction_matrix.shape[1])

Total interactions: 266254
Non-zero values: 266254
Total values: 15871108
Customers: 4334
Products: 3662

In [38]:
# Convert purchase quantities into binary interactions
# 1 = customer purchased the product
# 0 = customer did not purchase the product

interaction_binary = (interaction_matrix > 0).astype(int)

print("Binary Matrix Shape:", interaction_binary.shape)
print("Total Interactions:", interaction_binary.sum().sum())

Binary Matrix Shape: (4334, 3662)
Total Interactions: 266254

In [39]:
# Create a copy for training
train_matrix = interaction_binary.copy()

# Dictionary to store the held-out test product for each customer
test_items = {}

for customer_id in df_model['CustomerID'].unique():

    customer_data = (
        df_model[df_model['CustomerID'] == customer_id]
        .sort_values('InvoiceDate')
    )

    # Get the last product purchased by this customer
    last_product = str(customer_data.iloc[-1]['StockCode'])

    # Make sure the product exists in the interaction matrix
    if last_product in train_matrix.columns:

        test_items[customer_id] = last_product

        # Remove this product from customer's training history
        train_matrix.loc[customer_id, last_product] = 0

print("Customers:", len(train_matrix))
print("Products:", len(train_matrix.columns))
print("Test customers:", len(test_items))
print("Training interactions:", train_matrix.sum().sum())

Customers: 4334
Products: 3662
Test customers: 4334
Training interactions: 261920

In [40]:
from sklearn.decomposition import TruncatedSVD

# Train SVD model
svd = TruncatedSVD(
    n_components=50,
    random_state=42
)

customer_factors = svd.fit_transform(train_matrix)

product_factors = svd.components_

print("Customer Factors Shape:", customer_factors.shape)
print("Product Factors Shape:", product_factors.shape)
print("Explained Variance:", svd.explained_variance_ratio_.sum())

Customer Factors Shape: (4334, 50)
Product Factors Shape: (50, 3662)
Explained Variance: 0.27834139104750016

In [41]:
# Calculate predicted preference scores
predicted_scores = customer_factors @ product_factors

print("Predicted Scores Shape:", predicted_scores.shape)

Predicted Scores Shape: (4334, 3662)

In [44]:
def get_recommendations(customer_id, top_n=10):
    
    # Find customer's row position
    customer_index = train_matrix.index.get_loc(customer_id)
    
    # Get predicted scores for this customer
    scores = predicted_scores[customer_index]
    
    # Convert scores into a Series
    recommendation_scores = pd.Series(
        scores,
        index=train_matrix.columns
    )
    
    # Don't recommend products already present in training history
    purchased_products = train_matrix.loc[customer_id]
    recommendation_scores[purchased_products.values == 1] = -1
    
    # Return top recommendations
    return recommendation_scores.sort_values(
        ascending=False
    ).head(top_n)
    # Test recommendation for the most active customer
active_customer = interaction_binary.sum(axis=1).idxmax()

recommendations = get_recommendations(
    active_customer,
    top_n=10
)

print("Customer ID:", active_customer)
print("\nRecommended Products:")
print(recommendations)

Customer ID: 14911.0

Recommended Products:
StockCode
23239    0.657327
21158    0.652977
22402    0.648844
22521    0.636686
23091    0.578551
21746    0.533818
23089    0.526383
22913    0.517098
21716    0.514845
21159    0.498848
dtype: float64

In [45]:
# Create product information table
product_info = (
    df_model[['StockCode', 'Description']]
    .drop_duplicates('StockCode')
    .copy()
)

product_info['StockCode'] = product_info['StockCode'].astype(str)

# Convert recommendations into DataFrame
recommendation_df = recommendations.reset_index()

recommendation_df.columns = ['StockCode', 'Score']

recommendation_df['StockCode'] = recommendation_df['StockCode'].astype(str)

# Add product descriptions
recommendation_df = recommendation_df.merge(
    product_info,
    on='StockCode',
    how='left'
)

# Arrange columns
recommendation_df = recommendation_df[
    ['StockCode', 'Description', 'Score']
]

recommendation_df

  StockCode                        Description     Score
0     23239  SET OF 4 KNICK KNACK TINS POPPIES  0.657327
1     21158            MOODY GIRL DOOR HANGER   0.652977
2     22402  MAGNETS PACK OF 4 VINTAGE COLLAGE  0.648844
3     22521          CHILDS GARDEN TROWEL PINK  0.636686
4     23091         ZINC HERB GARDEN CONTAINER  0.578551
5     21746       SMALL RED RETROSPOT WINDMILL  0.533818
6     23089                  GLASS BON BON JAR  0.526383
7     22913        RED COAT RACK PARIS FASHION  0.517098
8     21716    BOYS VINTAGE TIN SEASIDE BUCKET  0.514845
9     21159            MOODY BOY  DOOR HANGER   0.498848

In [46]:
import numpy as np

def precision_at_k(actual, recommended, k=10):
    recommended = recommended[:k]
    
    if len(recommended) == 0:
        return 0.0
    
    hits = len(set(actual) & set(recommended))
    return hits / k


def recall_at_k(actual, recommended, k=10):
    recommended = recommended[:k]
    
    if len(actual) == 0:
        return 0.0
    
    hits = len(set(actual) & set(recommended))
    return hits / len(actual)


def ndcg_at_k(actual, recommended, k=10):
    recommended = recommended[:k]
    
    relevance = [
        1 if item in actual else 0
        for item in recommended
    ]
    
    dcg = sum(
        rel / np.log2(i + 2)
        for i, rel in enumerate(relevance)
    )
    
    ideal_relevance = sorted(relevance, reverse=True)
    
    idcg = sum(
        rel / np.log2(i + 2)
        for i, rel in enumerate(ideal_relevance)
    )
    
    if idcg == 0:
        return 0.0
    
    return dcg / idcg

In [49]:
# Evaluate the recommendation model

precision_scores = []
recall_scores = []
ndcg_scores = []

for customer_id, actual_item in test_items.items():

    recommendations = get_recommendations(
        customer_id,
        top_n=10
    )

    recommended_items = recommendations.index.astype(str).tolist()

    precision_scores.append(
        precision_at_k(
            [actual_item],
            recommended_items,
            k=10
        )
    )

    recall_scores.append(
        recall_at_k(
            [actual_item],
            recommended_items,
            k=10
        )
    )

    ndcg_scores.append(
        ndcg_at_k(
            [actual_item],
            recommended_items,
            k=10
        )
    )


print("Evaluation Results")
print("------------------")
print(f"Precision@10: {np.mean(precision_scores):.4f}")
print(f"Recall@10:    {np.mean(recall_scores):.4f}")
print(f"NDCG@10:      {np.mean(ndcg_scores):.4f}")

Evaluation Results
------------------
Precision@10: 0.0165
Recall@10:    0.1652
NDCG@10:      0.0986

In [50]:
# Calculate product popularity from training data
product_popularity = train_matrix.sum(axis=0)

# Get most popular products
popular_products = (
    product_popularity
    .sort_values(ascending=False)
    .index
    .astype(str)
    .tolist()
)

print("Top 10 Popular Products:")
print(popular_products[:10])

Top 10 Popular Products:
['22423', '85123A', '47566', '84879', '22720', '21212', '85099B', '22086', '22457', '23298']

In [51]:
# Evaluate Popularity Baseline

baseline_precision = []
baseline_recall = []
baseline_ndcg = []

for customer_id, actual_item in test_items.items():

    # Remove products already purchased by the customer
    purchased = set(
        train_matrix.loc[customer_id][
            train_matrix.loc[customer_id] == 1
        ].index.astype(str)
    )

    # Select top popular products not already purchased
    baseline_recommendations = [
        product
        for product in popular_products
        if product not in purchased
    ][:10]

    baseline_precision.append(
        precision_at_k(
            [actual_item],
            baseline_recommendations,
            k=10
        )
    )

    baseline_recall.append(
        recall_at_k(
            [actual_item],
            baseline_recommendations,
            k=10
        )
    )

    baseline_ndcg.append(
        ndcg_at_k(
            [actual_item],
            baseline_recommendations,
            k=10
        )
    )


print("Popularity Baseline Results")
print("---------------------------")
print(f"Precision@10: {np.mean(baseline_precision):.4f}")
print(f"Recall@10:    {np.mean(baseline_recall):.4f}")
print(f"NDCG@10:      {np.mean(baseline_ndcg):.4f}")

Popularity Baseline Results
---------------------------
Precision@10: 0.0053
Recall@10:    0.0533
NDCG@10:      0.0276

In [52]:
comparison = pd.DataFrame({
    'Model': [
        'SVD Recommender',
        'Popularity Baseline'
    ],
    'Precision@10': [
        np.mean(precision_scores),
        np.mean(baseline_precision)
    ],
    'Recall@10': [
        np.mean(recall_scores),
        np.mean(baseline_recall)
    ],
    'NDCG@10': [
        np.mean(ndcg_scores),
        np.mean(baseline_ndcg)
    ]
})

comparison

                 Model  Precision@10  Recall@10   NDCG@10
0      SVD Recommender      0.016521   0.165205  0.098639
1  Popularity Baseline      0.005330   0.053299  0.027605